# Generated by Django 2.0.5 on 2020-05-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('tasks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, to='courses.Course', verbose_name='Пройденные курсы'),
        ),
        migrations.AddField(
            model_name='student',
            name='test',
            field=models.ManyToManyField(to='tasks.Test'),
        ),
    ]
