# Generated by Django 2.0.5 on 2020-05-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200504_1345'),
        ('users', '0004_auto_20200504_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, to='courses.Course', verbose_name='Пройденные курсы'),
        ),
    ]
