# Generated by Django 2.0.5 on 2020-05-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('courses', '0002_course_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='test_in_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Test', verbose_name='Тест'),
        ),
    ]
