# Generated by Django 2.0.5 on 2020-05-04 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
        ('courses', '0003_course_test_in_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Сообщение')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('read', models.BooleanField(default=False, verbose_name='Просмотренно')),
            ],
            options={
                'verbose_name': 'Сообщение в задании',
                'verbose_name_plural': 'Сообщения в задании',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала выполнения задания')),
                ('date_end', models.DateTimeField(verbose_name='Дата окончания выполнения задания')),
                ('active', models.BooleanField(default=False, verbose_name='Вывести задание')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskRealization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('success', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.Task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Выполненное задание',
                'verbose_name_plural': 'Выполненные задания',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='counter_tasks',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заданий'),
        ),
        migrations.AddField(
            model_name='task',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.Course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='task',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.Test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='messagestask',
            name='task_realization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realization_task', to='courses.TaskRealization', verbose_name='Выполнение'),
        ),
        migrations.AddField(
            model_name='messagestask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
    ]
