# Generated by Django 2.0.5 on 2020-05-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200510_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagestask',
            name='task_realization',
        ),
        migrations.RemoveField(
            model_name='messagestask',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='course',
        ),
        migrations.RemoveField(
            model_name='taskrealization',
            name='student',
        ),
        migrations.RemoveField(
            model_name='taskrealization',
            name='task',
        ),
        migrations.DeleteModel(
            name='MessagesTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskRealization',
        ),
    ]
