# Generated by Django 2.0.5 on 2020-04-25 15:25

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200425_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['sort'], 'verbose_name': 'Контент'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['sort'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AddField(
            model_name='content',
            name='sort',
            field=courses.fields.SortField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='sort',
            field=courses.fields.SortField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
