# Generated by Django 2.0.5 on 2020-05-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default=0, max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
